SI_units = {
    "AREAUNIT": "SQUARE_METRE",
    "ENERGYUNIT": "JOULE",
    "FORCEUNIT": "NEWTON",
    "FREQUENCYUNIT": "HERTZ",
    "LENGTHUNIT": "METRE",
    "MASSUNIT": "GRAM",
    "PLANEANGLEUNIT": "RADIAN",
    "POWERUNIT": "WATT",
    "PRESSUREUNIT": "PASCAL",
    "SOLIDANGLEUNIT": "STERADIAN",
    "THERMODYNAMICTEMPERATUREUNIT": "KELVIN",
    "TIMEUNIT": "SECOND",
    "VOLUMEUNIT": "CUBIC_METRE"
}
